In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
17   22  Female     Poor        UG       Yes
46   64  Female     Poor        PG        No
5    31  Female  Average    School       Yes
22   18  Female     Poor        PG       Yes
11   74    Male     Good        UG       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [12]:
X_train = oe.transform(X_train)

NameError: name 'X_train' is not defined

In [9]:
oe.fit(X_train)

NameError: name 'X_train' is not defined

In [ ]:
X_train

In [ ]:
oe.categories_

In [ ]:
X_train

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

In [ ]:
le.classes_

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train